# Generated by Django 3.1.2 on 2020-10-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201029_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='newstory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='newstory',
            name='url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='newstory',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
