# Generated by Django 3.1.2 on 2020-10-31 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201031_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstory',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
