# Generated by Django 3.1.2 on 2020-11-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newstory_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstory',
            name='sum',
            field=models.FloatField(default=0),
        ),
    ]
