# Generated by Django 3.1.2 on 2020-12-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newstory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='storyid',
            field=models.IntegerField(default=0),
        ),
    ]
