# Generated by Django 3.1.2 on 2020-12-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_comments_storyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstory',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
