# Generated by Django 3.1.2 on 2020-12-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20201206_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstory',
            name='ConfidenceScore',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='newstory',
            name='language',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
